// swift-tools-version:5.9.0
// =============================================================================
// DO NOT EDIT THIS FILE IN THIS REPO.
// Generated by Shard. Root package: elix-toolchain
// =============================================================================

import PackageDescription
import CompilerPluginSupport

let package = Package(
    name: "ComposablePipelines",
    platforms: [
        .macOS("14.0"),
        .iOS("17.0"),
    ],
    products: [
        .library(name: "ComposablePipelines", targets: ["ComposablePipelines"]),
        .library(name: "PipelineAST", targets: ["PipelineAST"]),
        .library(name: "PipelineDSL", targets: ["PipelineDSL"]),
        .library(name: "PipelineCompiler", targets: ["PipelineCompiler"]),
        .library(name: "ExecutionEngine", targets: ["ExecutionEngine"]),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-syntax", from: "600.0.0"),
        .package(url: "https://github.com/huggingface/AnyLanguageModel", from: "0.8.0"),
    ],
    targets: [
        .target(
            name: "ExecutionEngine",
            dependencies: ["PipelineAST", "PipelineCompiler"],
            path: "Sources/ComposablePipelines/ExecutionEngine",
        ),
        .target(
            name: "PipelineAST",
            path: "Sources/ComposablePipelines/PipelineAST",
        ),
        .target(
            name: "PipelineDSL",
            dependencies: ["PipelineAST", "PipelinePreviewMacro", .product(name: "AnyLanguageModel", package: "AnyLanguageModel")],
            path: "Sources/ComposablePipelines/PipelineDSL",
        ),
        .macro(
            name: "PipelinePreviewMacro",
            dependencies: [.product(name: "SwiftSyntaxMacros", package: "swift-syntax"), .product(name: "SwiftCompilerPlugin", package: "swift-syntax"), .product(name: "SwiftSyntax", package: "swift-syntax")],
            path: "Sources/ComposablePipelines/PipelinePreviewMacro",
        ),
        .target(
            name: "PipelineCompiler",
            dependencies: ["PipelineAST"],
            path: "Sources/ComposablePipelines/PipelineCompiler",
        ),
        .target(
            name: "ComposablePipelines",
            dependencies: ["PipelineAST", "PipelineDSL", "PipelineCompiler", "ExecutionEngine"],
            path: "Sources/ComposablePipelines/ComposablePipelines",
        ),
    ]
)
